// Generates lib/booking/emailTemplates.ts from the designed HTML in
// email-templates/*.html. Bundling as a TS string module (vs reading files at
// runtime) keeps it reliable on serverless. Re-run after editing any email:
//   npm run build-emails

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

const SRC = "email-templates";
const OUT = "lib/booking/emailTemplates.ts";

const NAMED = {
  amp: "&", mdash: "—", ndash: "–", nbsp: " ", hellip: "…",
  rarr: "→", middot: "·", quot: '"', apos: "'", lt: "<", gt: ">", copy: "©",
};

// Decode HTML entities — only needed for the plain-text subject line.
function decode(s) {
  return s
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&([a-zA-Z]+);/g, (_, n) => NAMED[n] ?? `&${n};`);
}

const files = readdirSync(SRC).filter((f) => f.endsWith(".html"));
const entries = files
  .map((f) => {
    const html = readFileSync(join(SRC, f), "utf8");
    const num = f.match(/EM-(\d+)/)[1];
    const subj = html.match(/Subject:\s*(.+)/);
    return { key: `EM${num}`, n: Number(num), subject: decode((subj ? subj[1] : "").trim()), html };
  })
  .sort((a, b) => a.n - b.n);

let ts =
  "// AUTO-GENERATED by scripts/build-emails.mjs from email-templates/*.html.\n" +
  "// Do not edit by hand — edit the HTML and re-run `npm run build-emails`.\n\n";
ts += `export type EmailKey = ${entries.map((e) => `"${e.key}"`).join(" | ")};\n\n`;
ts += "export const EMAIL_TEMPLATES: Record<EmailKey, { subject: string; html: string }> = {\n";
for (const e of entries) {
  ts += `  ${e.key}: { subject: ${JSON.stringify(e.subject)}, html: ${JSON.stringify(e.html)} },\n`;
}
ts += "};\n";

writeFileSync(OUT, ts);
console.log(`Wrote ${OUT} — ${entries.length} templates: ${entries.map((e) => e.key).join(", ")}`);
